<a href="https://colab.research.google.com/github/nimish08/summer19-ML/blob/master/randomforesttt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
# loading data
df=pd.read_csv('http://13.234.66.67/summer19/datasets/social.csv')

In [0]:
# schema 
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [0]:
#  top 5 rows
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [0]:
# using user id
filterdata=df.iloc[0:,2:].values

In [0]:
filterdata

array([[   19, 19000,     0],
       [   35, 20000,     0],
       [   26, 43000,     0],
       ...,
       [   50, 20000,     1],
       [   36, 33000,     0],
       [   49, 36000,     1]])

In [0]:
# now we can apply traning test
features=filterdata[0:,0:2]

In [0]:
features

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [0]:
# label finding
label=filterdata[0:,2]

In [0]:
# training and testing
from sklearn.model_selection import train_test_split


In [0]:
X,x,Y,y=train_test_split(features,label,test_size=0.2)

In [0]:
# now apply features scaling
from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler()

In [0]:
# apply scaling in traing data only
X=sc.fit_transform(X)

In [0]:
# testing data scaling
x=sc.transform(x)

In [0]:
type(x)

numpy.ndarray

In [0]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [0]:
# random forest cal withh number of DecosionTree
Rclf=RandomForestClassifier(n_timators=20)

In [0]:
# now training 
trained=Rclf.fit(X,Y)

In [0]:
# now predicting
output=trained.predict(x)

In [0]:
y

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [0]:
# to calculate accuracy
from sklearn.metrics import accuracy_score

In [0]:
accuracy_score(output,y)

0.9125